config/routes.rb
Rails.application.routes.draw do
  # get 'departments/index'
  # get 'departments/show'
  # get 'departments/new'
  # get 'departments/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :departments do
    resources :items
  end

  resources :items do
    resources :comments
  end
  root 'departments#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  before_save :check_author
  belongs_to :item

  def check_author
    if self.author.blank?
      self.author = "anon"
    end
  end
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_item
  def new
    @comment = Comment.new
  end

  def create
    @comment = @item.comments.new(comment_params)
    if @comment.save
      redirect_to department_item_path(@item.department_id, @item)
    else  
      render :new
    end
  end


  private
    def set_item
      @item = Item.find(params[:item_id])
    end

    def comment_params
      params.require(:comment).permit(:author, :body)
    end

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  def index
    @departments = Department.all
  end

  def show
  end

  def destroy
    @department.destroy
    redirect_to departments_path
  end

  def new
    @department = Department.new
    render partial: "depart"
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_path
    else  
      render :new
    end
  end

  def edit
    render partial: "depart"
  end

  def update
    if @department.update(department_params)
      redirect_to departments_path
    else  
      render :edit
    end
  end

  private
    def set_department
      @department = Department.find(params[:id])
    end

    def department_params
      params.require(:department).permit(:name, :phone)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  def index
    # @department = Department.find(params[:department_id])
    @items = @department.items
  end

  def show

  end

  def new 
    @item = Item.new(department_id: params[:department_id])
    render partial: 'form'
  end 
  def create
    @item = @department.items.new(item_params)
    if @item.save
      redirect_to department_items_path(@department)
    else  
      render :new 
    end
  end

  def edit
    render partial: 'form'
  end

  def update
    if @item.update(item_params)
      redirect_to department_items_path(@department)
    else  
      render :edit 
    end
  end

  def destroy
    @item.destroy 
    redirect_to department_items_path(@department)
  end

  private
    def item_params
      params.require(:item).permit(:name, :description, :cost)
    end
    def set_department
      @department = Department.find(params[:department_id])
    end
    def set_item
      @item = Item.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/comments/_comment.html.erb
app/views/comments/new.html.erb


  
<hr />
<p>Author: <%= comment.author %></p>
<p><strong><%= comment.body %></strong></p>
</hr>

app/views/comments/edit.html.erb
<h1>Comment#edit</h1>
<p>Find me in app/views/comment/edit.html.erb</p>

app/views/comments/new.html.erb
<h1>Comment#new</h1>
<p>Find me in app/views/comment/new.html.erb</p>
<h1>Add A comment</h1>
<%= form_for [@item, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <br />
  <%= f.label :author %>
  <%= f.text_field :author, placeholder: 'Leave Blank To Remain Anonymous' %>
  <br />
  <%= f.submit %>
<% end %>

app/views/departments/_depart.html.erb
<h1><%= @department.id ? 'Edit Department' : 'Create Department' %></h1>
<%= link_to  "back to departments", departments_path %>
<hr />
<%= form_for [@department] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :phone %>
  <%= f.text_field :phone, required: true %>

  <%= f.submit %>
<% end %>

app/views/departments/edit.html.erb
<h1>Departments#edit</h1>
<p>Find me in app/views/departments/edit.html.erb</p>

app/views/departments/index.html.erb
<%= link_to "Create Department", new_department_path%>

<% @departments.each do |department|%>
  <h4><%= department.name%></h4>
  <h4><%= link_to "View", department_items_path(department)%></h4>
  <h4><%= link_to "Update", edit_department_path(department)%></h4>
  <h4><%= link_to "Delete", department, method: :delete %></h4>
<% end %>

app/views/departments/new.html.erb
<h1>Departments#new</h1>
<p>Find me in app/views/departments/new.html.erb</p>

app/views/departments/show.html.erb
<h1>Departments#show</h1>
<p>Find me in app/views/departments/show.html.erb</p>

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit Item' : 'Create Item' %></h1>
<%= link_to  "back to items", department_items_path %>
<hr />
<%= form_for [@department, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :description %>
  <%= f.text_area :description, required: true %>
  <%= f.label :cost %>
  <%= f.text_field :cost, required: true%>
  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<%= link_to "Add Item", new_department_item_path(@department)%>
<h1>Department Type: <%= @department.name %></h1>



<% @department.items.each do |item|%>
  <h3><%= link_to item.name, [@department, item] %></h3>
  <h3><%= item.description%></h3>
  <h3><%= item.cost%></h3>
<% end %>
<%= link_to "Go Back to Departments", departments_path %>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1><%= @department.name %> - <%= @item.name%></h1>
<h2><%= @item.cost%></h2>
<h3><%= @item.description %></h3>
<%= link_to "Edit Item", edit_department_item_path([@department, @item])%>
<%= link_to "Delete Item", [@department, @item], method: :delete %>
<%= link_to "Back to Items", department_items_path(@department)%>
<%= link_to 'Add Comment', new_item_comment_path(@item)%>


<% @item.comments.each do |comment|%>
  <%= render 'comments/comment', {comment: comment}%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Depart</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>